const students = [
  {
    name: "Abdul Rahaman",
    image: "images/download1.jpg",
    Course: "Computer Science",
    age: 20,
    level: 400,
    status: "Active",
    "Student id": "DTIT250001",
    department: "Computer Science",
    graduationyear: 2022,
    currentGPA: 3.8,
    CreditEarned: "84 / 120",
    attendance: 20,
    studyStreak: "5 days",
    academicAdvisor: "Rahaman Abdul",
    AdvisorEmail: "rahamaabdul@gamil.com",
    Programme: "Bsc Computer Science",
  },
  {
    name: "Mariam Asante",
    image: "images/download1.jpg",
    Course: "Computer Science",
    age: 19,
    level: 300,
    status: "Active",
    "Student id": "DTIT250002",
    department: "Computer Science",
    graduationyear: 2023,
    currentGPA: 3.6,
    CreditEarned: "72 / 120",
    attendance: 85,
    studyStreak: "7 days",
    academicAdvisor: "Dr. Kwaku Mensah",
    AdvisorEmail: "kwaku.mensah@school.edu",
    Programme: "Bsc Computer Science",
  },
  {
    name: "Kwame Boateng",
    image: "images/download1.jpg",
    Course: "Computer Science",
    age: 21,
    level: 400,
    status: "On Leave",
    "Student id": "DTIT250003",
    department: "Computer Science",
    graduationyear: 2022,
    currentGPA: 3.4,
    CreditEarned: "68 / 120",
    attendance: 76,
    studyStreak: "3 days",
    academicAdvisor: "Prof. Grace Owusu",
    AdvisorEmail: "grace.owusu@school.edu",
    Programme: "Bsc Computer Science",
  },
  {
    name: "Naa Afi",
    image: "images/download1.jpg",
    Course: "Information Technology",
    age: 18,
    level: 200,
    status: "Active",
    "Student id": "DTIT250004",
    department: "Information Technology",
    graduationyear: 2024,
    currentGPA: 3.9,
    CreditEarned: "90 / 120",
    attendance: 92,
    studyStreak: "10 days",
    academicAdvisor: "Dr. Yaw Kofi",
    AdvisorEmail: "yaw.kofi@school.edu",
    Programme: "Bsc Information Technology",
  },
  {
    name: "Daniel Mensah",
    image: "images/download1.jpg",
    Course: "Software Engineering",
    age: 22,
    level: 400,
    status: "Active",
    "Student id": "DTIT250005",
    department: "Software Engineering",
    graduationyear: 2022,
    currentGPA: 3.7,
    CreditEarned: "80 / 120",
    attendance: 88,
    studyStreak: "6 days",
    academicAdvisor: "Mrs. Cecilia Osei",
    AdvisorEmail: "cecilia.osei@school.edu",
    Programme: "Bsc Software Engineering",
  },
  {
    name: "Efua Johnson",
    image: "images/download1.jpg",
    Course: "Cybersecurity",
    age: 20,
    level: 300,
    status: "Active",
    "Student id": "DTIT250006",
    department: "Cybersecurity",
    graduationyear: 2023,
    currentGPA: 3.5,
    CreditEarned: "70 / 120",
    attendance: 82,
    studyStreak: "8 days",
    academicAdvisor: "Dr. Michael Nyarko",
    AdvisorEmail: "michael.nyarko@school.edu",
    Programme: "Bsc Cybersecurity",
  },
  {
    name: "Kojo Addo",
    image: "images/download1.jpg",
    Course: "Computer Science",
    age: 23,
    level: 500,
    status: "Graduating",
    "Student id": "DTIT250007",
    department: "Computer Science",
    graduationyear: 2021,
    currentGPA: 3.8,
    CreditEarned: "96 / 120",
    attendance: 90,
    studyStreak: "12 days",
    academicAdvisor: "Prof. Esi Quartey",
    AdvisorEmail: "esi.quartey@school.edu",
    Programme: "Bsc Computer Science",
  },
  {
    name: "Sena Kwarteng",
    image: "images/download1.jpg",
    Course: "Data Science",
    age: 19,
    level: 300,
    status: "Active",
    "Student id": "DTIT250008",
    department: "Data Science",
    graduationyear: 2023,
    currentGPA: 3.6,
    CreditEarned: "75 / 120",
    attendance: 84,
    studyStreak: "4 days",
    academicAdvisor: "Dr. Hannah Yeboah",
    AdvisorEmail: "hannah.yeboah@school.edu",
    Programme: "Bsc Data Science",
  },
  {
    name: "Selorm Tetteh",
    image: "images/download1.jpg",
    Course: "Computer Engineering",
    age: 21,
    level: 400,
    status: "Active",
    "Student id": "DTIT250009",
    department: "Computer Engineering",
    graduationyear: 2022,
    currentGPA: 3.7,
    CreditEarned: "82 / 120",
    attendance: 87,
    studyStreak: "9 days",
    academicAdvisor: "Mr. Emmanuel Kuma",
    AdvisorEmail: "emmanuel.kuma@school.edu",
    Programme: "Bsc Computer Engineering",
  },
  {
    name: "Adwoa Owusu",
    image: "images/download1.jpg",
    Course: "Artificial Intelligence",
    age: 20,
    level: 300,
    status: "Active",
    "Student id": "DTIT250010",
    department: "Artificial Intelligence",
    graduationyear: 2023,
    currentGPA: 3.9,
    CreditEarned: "88 / 120",
    attendance: 91,
    studyStreak: "11 days",
    academicAdvisor: "Dr. Samuel Kyei",
    AdvisorEmail: "samuel.kyei@school.edu",
    Programme: "Bsc Artificial Intelligence",
  },
];
