export let students = [
  {
    name: "Abdul Rahaman",
    image: "../images/download1.jpg",
    Course: "Computer Science",
    password: "2020ww",
    level: 400,
    status: "Active",
    StudentId: "DTIT250001",
    department: "Computer Science",
    GraduationYear: 2022,
    currentGPA: 3.8,
    CreditEarned: "84 / 120",
    attendance: 20,
    studyStreak: "5 days",
    academicAdvisor: "Rahaman Abdul",
    AdvisorEmail: "rahamaabdul@gamil.com",
    Programme: "Bsc Computer Science",
  },
  {
    name: "Mariam Asante",
    image: "../images/download1.jpg",
    Course: "Computer Science",
    age: 19,
    level: 300,
    status: "Active",
    StudentId: "DTIT250002",
    password: "2020ww",
    department: "Computer Science",
    GraduationYear: 2023,
    currentGPA: 3.6,
    CreditEarned: "72 / 120",
    attendance: 85,
    studyStreak: "7 days",
    academicAdvisor: "Dr. Kwaku Mensah",
    AdvisorEmail: "kwaku.mensah@school.edu",
    Programme: "Bsc Computer Science",
  },
  {
    name: "Kwame Boateng",
    image: "../images/download1.jpg",
    Course: "Computer Science",
    age: 21,
    level: 400,
    status: "On Leave",
    StudentId: "DTIT250003",
    password: "2020ww",
    department: "Computer Science",
    GraduationYear: 2022,
    currentGPA: 3.4,
    CreditEarned: "68 / 120",
    attendance: 76,
    studyStreak: "3 days",
    academicAdvisor: "Prof. Grace Owusu",
    AdvisorEmail: "grace.owusu@school.edu",
    Programme: "Bsc Computer Science",
  },
  {
    name: "Naa Afi",
    image: "../images/download1.jpg",
    Course: "Information Technology",
    age: 18,
    level: 200,
    status: "Active",
    StudentId: "DTIT250004",
    password: "2020ww",
    department: "Information Technology",
    GraduationYear: 2024,
    currentGPA: 3.9,
    CreditEarned: "90 / 120",
    attendance: 92,
    studyStreak: "10 days",
    academicAdvisor: "Dr. Yaw Kofi",
    AdvisorEmail: "yaw.kofi@school.edu",
    Programme: "Bsc Information Technology",
  },
  {
    name: "Daniel Mensah",
    image: "../images/download1.jpg",
    Course: "Software Engineering",
    age: 22,
    level: 400,
    status: "Active",
    StudentId: "DTIT250005",
    password: "2020ww",
    department: "Software Engineering",
    GraduationYear: 2022,
    currentGPA: 3.7,
    CreditEarned: "80 / 120",
    attendance: 88,
    studyStreak: "6 days",
    academicAdvisor: "Mrs. Cecilia Osei",
    AdvisorEmail: "cecilia.osei@school.edu",
    Programme: "Bsc Software Engineering",
  },
  {
    name: "Efua Johnson",
    image: "../images/download1.jpg",
    Course: "Cybersecurity",
    age: 20,
    level: 300,
    status: "Active",
    StudentId: "DTIT250006",
    password: "2020ww",
    department: "Cybersecurity",
    GraduationYear: 2023,
    currentGPA: 3.5,
    CreditEarned: "70 / 120",
    attendance: 82,
    studyStreak: "8 days",
    academicAdvisor: "Dr. Michael Nyarko",
    AdvisorEmail: "michael.nyarko@school.edu",
    Programme: "Bsc Cybersecurity",
  },
  {
    name: "Kojo Addo",
    image: "../images/download1.jpg",
    Course: "Computer Science",
    age: 23,
    level: 500,
    status: "Graduating",
    StudentId: "DTIT250007",
    password: "2020ww",
    department: "Computer Science",
    GraduationYear: 2021,
    currentGPA: 3.8,
    CreditEarned: "96 / 120",
    attendance: 90,
    studyStreak: "12 days",
    academicAdvisor: "Prof. Esi Quartey",
    AdvisorEmail: "esi.quartey@school.edu",
    Programme: "Bsc Computer Science",
  },
  {
    name: "Sena Kwarteng",
    image: "../images/download1.jpg",
    Course: "Data Science",
    age: 19,
    level: 300,
    status: "Active",
    StudentId: "DTIT250008",
    password: "2020ww",
    department: "Data Science",
    GraduationYear: 2023,
    currentGPA: 3.6,
    CreditEarned: "75 / 120",
    attendance: 84,
    studyStreak: "4 days",
    academicAdvisor: "Dr. Hannah Yeboah",
    AdvisorEmail: "hannah.yeboah@school.edu",
    Programme: "Bsc Data Science",
  },
  {
    name: "Selorm Tetteh",
    image: "../images/download1.jpg",
    Course: "Computer Engineering",
    age: 21,
    level: 400,
    status: "Active",
    StudentId: "DTIT250009",
    password: "2020ww",
    department: "Computer Engineering",
    GraduationYear: 2022,
    currentGPA: 3.7,
    CreditEarned: "82 / 120",
    attendance: 87,
    studyStreak: "9 days",
    academicAdvisor: "Mr. Emmanuel Kuma",
    AdvisorEmail: "emmanuel.kuma@school.edu",
    Programme: "Bsc Computer Engineering",
  },
  {
    name: "Adwoa Owusu",
    image: "../images/download1.jpg",
    Course: "Artificial Intelligence",
    age: 20,
    level: 100,
    status: "Active",
    StudentId: "DTIT250010",
    password: "2020ww",
    department: "Artificial Intelligence",
    GraduationYear: 2022,
    currentGPA: 0,
    CreditEarned: "0 / 120",
    attendance: 1,
    studyStreak: "1 days",
    academicAdvisor: "Dr. Samuel Kyei",
    AdvisorEmail: "samuel.kyei@school.edu",
    Programme: "Bsc Artificial Intelligence",
  },
];

function logIn() {
  const Id = document.querySelector(".id").value;
  const Password = document.querySelector(".password").value;

  const inputElement = students.find((student) => {
    return student.StudentId === Id && student.password === Password;
  });

  if (inputElement) {
    localStorage.setItem("Id", Id);
    alert("WELCOME");
    window.location.href = "index.html";
  } else {
    alert("Invalid StudentID or Password");
  }
}
const loginBtn = document.querySelector(".loginBtn");
if (loginBtn) {
  loginBtn.addEventListener("click", logIn);
}
